<?php
/**
 * @file
 * Field Types are independant of Tripal Entity Types and, as such, can be used on multiple
 * Tripal Content Types. For example, Drupal Field types include "textfield", "image field",
 * etc. which obviously apply to multiple content types. A Field Instance refers to a
 * particular instantiation of of field type on a bundle. For example, the body of a
 * "Page" content type is a field instance of the textarea field type.
 */

// Includes the trp_render_as_markdown() function for rendering markdown pages.
include(drupal_get_path('module', 'trpexp_fields') . '/../includes/markdown_parse.inc');

// Includes all non-class field functions.
include('includes/trpexp_fields.fields.inc');

/**
 * Implements hook_menu().
 */
function trpexp_fields_menu() {
  $items = array();

  $tutorial_path = drupal_get_path('module', 'trpexp_fields') . '/tutorial/';

  $items['tripal-example/fields'] = array(
    'title' => 'Examples: Tripal Fields',
    'description' => 'Examples on how to develop custom fields.',
    'page callback' => 'trp_render_as_markdown',
    'page arguments' => array( $tutorial_path . 'trpexp_fields_index.md' ),
    'access arguments' => array('access content'),
  );

  $items['tripal-example/fields/custom-field'] = array(
    'title' => 'Custom Tripal Field, Widget & Formatter',
    'description' => 'Tutorial on how to create a custom Tripal Field, widget & formatter.',
    'page callback' => 'trp_render_as_markdown',
    'page arguments' => array( $tutorial_path . 'trpexp_fields_custom_field.md' ),
    'access arguments' => array('access content'),
  );

  return $items;
}

